### ISSUE TITLE
Errors while installing ubuntu on HiKey960

### ISSUE THREAD

**Issue by ivsrihari** [ARM-software/Tool-Solutions#1]
Hi,
We are trying to install Ubuntu on Hikey960 using instructions at link below.
https://github.com/ARM-software/Tool-Solutions/tree/master/ml-tool-examples/hikey960-ubuntu

After recovery is successfully done, flashboot.sh is executed and we see below error. Can you please check this issue?

% ./fastboot.sh 
target reported max download size of 134217728 bytes
sending 'ptable' (196 KB)...
OKAY [  0.102s]
writing 'ptable'...
OKAY [  0.016s]
finished. total time: 0.119s
target reported max download size of 134217728 bytes
sending 'xloader' (151 KB)...
OKAY [  0.042s]
writing 'xloader'...
OKAY [  0.281s]
finished. total time: 0.323s
target reported max download size of 134217728 bytes
sending 'fastboot' (3346 KB)...
OKAY [  0.129s]
writing 'fastboot'...
FAILED (remote: No such partition.)
finished. total time: 0.130s

**Comment by zachlas** [comment]
Hello,

Thanks for the feedback. We have tried to replicate this issue on several different boards but our flashbooting is always successful. Can you verify that the correct boot files are in the 'tools-images-hikey960' directory? These all the .img files that are mentioned in 'fastboot.sh'. Notably the 'hisi-fastboot.img' file. 

If the relevant files are all present and the issue persists, try to follow these steps exactly when powering up and down the board:
To power up:

1. Move switches to correct mode (Recovery, Fastboot, or Normal)
2. Ensure USB-C cable is plugged in
3. Power on

To power off:

1. Press the 'Power key' to turn off the board safely (behind one of the USB ports)
2. Wait 5 seconds for the board to power off
3. Unplug the power cable

**Comment by jasonrandrews** [comment]
Another link to check for solutions: https://discuss.96boards.org/t/hikey960-android-fastboot-failed-remote-no-such-partition/7326

**Comment by ivsrihari** [comment]
Thank you @jasonrandrews and @zachlas.
I followed recovery procedure at https://github.com/96boards-hikey/tools-images-hikey960/blob/master/README.md and then followed steps (without power cycling the board/without changing switch settings) under section "Fastboot mode to flash the remaining images" (https://github.com/ARM-software/Tool-Solutions/tree/master/ml-tool-examples/hikey960-ubuntu) to get my board up and running.
