### ISSUE TITLE
unauthorized: authentication required

### ISSUE THREAD

**Issue by magicse** [ARM-software/Tool-Solutions#101]
with QNAP docker station  and with this image https://hub.docker.com/r/linaro/tensorflow-arm-neoverse-n1 - I get 
unauthorized: authentication required

**Comment by nSircombe** [comment]
Hi @magicse,

Thanks for getting in touch.
I don't think the images on Linaro's Docker Hub have been updated recently, but newer images are available from Arm SWDev's Docker Hub here: https://hub.docker.com/r/armswdev/tensorflow-arm-neoverse-n1

I'd recommend you give those newer builds a try as a first step.

If you still have issues, then please add some additional information to the ticket here:
- Some more system details, OS, OS version and CPU
- Docker version
- The steps you took from pulling the image to encountering the error
- stderr/stdout up to and including the error

Many thanks.

**Comment by magicse** [comment]
CPU armv7

**Comment by nSircombe** [comment]
Hi @magicse,

I'm afraid those images are built with Neoverse-N1 targets in mind, and so assume at least Armv8.2-a.

**Comment by magicse** [comment]
Ah ok . Thank You for helping.

**Comment by nSircombe** [comment]
No problem.
