### ISSUE TITLE
conflicting torch and torch vision versions

### ISSUE THREAD

**Issue by EgleGrublyte** [ARM-software/Tool-Solutions#116]
Hi there, 

Currently, the build armswdev/pytorch-arm-neoverse:r22.02-torch-1.10.0-openblas installs:
torch==1.10.0a0+git36449ea
torchvision==0.9.1

However, according to pypi  https://pypi.org/project/torchvision/ these two torch and torchvision versions are not compatible.

**Comment by nSircombe** [comment]
Hi @EgleGrublyte,

Thanks for pointing this out. You're right, Torchvision is overdue an update. I'll get it fixed.
