### ISSUE TITLE
Installation of latest Ubuntu OS on Hikey960 boards

### ISSUE THREAD

**Issue by ivsrihari** [ARM-software/Tool-Solutions#129]
Hi,

I am trying to see if there are instructions to install latest version of Ubuntu OS on Hikey960 board.  I have also noticed that instructions to install Ubuntu on hikey960 board are no longer available at the link - https://github.com/ARM-software/Tool-Solutions/tree/master/ml-tool-examples/hikey960-ubuntu
We were able to install Ubuntu 16.04 earlier with these instructions. I am trying to check if we can install Ubuntu 20.04 or higher on Hikey960 board.

Thanks,
Srihari

**Comment by jasonrandrews** [comment]
Hi, 

Unfortunately, we were not able to keep up the Ubuntu version on the HiKey 960 boards. There doesn't seem to be any active development for the board, so we have removed the examples. 

Thanks.
