### ISSUE TITLE
Add prebuilt TensorFlow Serving image to Docker Hub

### ISSUE THREAD

**Issue by fumoboy007** [ARM-software/Tool-Solutions#153]
Hi! I am interested in using [TensorFlow Serving](https://www.tensorflow.org/tfx/guide/serving) to make predictions with a saved model.

I see that the build script in this repository [supports](https://github.com/ARM-software/Tool-Solutions/blob/main/docker/tensorflow-aarch64/README.md#building-a-tensorflow-serving-image) building a TensorFlow Serving image. I was wondering if y’all could add a prebuilt TensorFlow Serving image to Docker Hub so that people don’t need to build their own images, similar to the full TensorFlow [image](https://hub.docker.com/r/armswdev/tensorflow-arm-neoverse).

**Comment by nSircombe** [comment]
Hi @fumoboy007,

Thanks for your interest in our TF builds. 
The TF serving build option hasn't been actively maintained, and needs to be updated for the latest TF release, we would also need to make sure we're testing the Serving build, so there's some work required which is currently not scheduled and there are currently no plans to add a TF serving build to the images on Dockerhub.

**Comment by fumoboy007** [comment]
Thanks for the info about your plans, @nSircombe!

Is this effort something that ARM should own or should it be owned by Google given that they [already have](https://hub.docker.com/r/tensorflow/serving) prebuilt TensorFlow Serving images for x86?

**Comment by nSircombe** [comment]
Hi @fumoboy007,

These build instructions, and the finished images on Docker Hub aren't intended for 'production' use (see the note in https://github.com/ARM-software/Tool-Solutions/blob/main/docker/tensorflow-aarch64/README.md). They include features / optimisations in development, and not available (yet) in an upstream release of the libs/frameworks. The images and are intended only for evaluation purposes really.

When it comes to providing release builds in perpetuity, that's not something that we would naturally expect to lead. For example the recent availability of TF wheels is underpinned by work from a number of Partners (https://blog.tensorflow.org/2022/09/announcing-tensorflow-official-build-collaborators.html).

**Comment by fumoboy007** [comment]
@nSircombe Good to know, thanks! Whom among the partners (Google, Intel, AWS, ARM, and Linaro) should I ask for a prebuilt ARM64 TensorFlow Serving image?

**Comment by nSircombe** [comment]
Hi @fumoboy007,
In the first instance, you could raise an issue on tensorflow/serving's GitHub site and see if Google have any comment.
