### ISSUE TITLE
PL011 UART not in Peripheral region for Cortex-M hello world

### ISSUE THREAD

**Issue by flit** [ARM-software/Tool-Solutions#19]
https://github.com/ARM-software/Tool-Solutions/blob/12822ec5f63c2395d57e0e683ee0f392acbe40ac/hello-world_fast-models/Cortex-M/system/Cortex-M.lisa#L22

The v8-M architecture defines the address range of 0x4000_0000–0x0x5FFF_FFFF as the Peripheral region in the system address map. Peripherals should normally be placed in this address range so they have the correct memory type (Device, nGnRE) and attributes (XN, non-cacheable). 0xA000_0000–0xDFFFFFFF are also Device regions, but the Peripheral region is preferred.

**Comment by jasonrandrews** [comment]
Good to know and noted if there are future changes to the system.
