### ISSUE TITLE
scaling_max_freq stuck at lowest available frequency on Hikey 960

### ISSUE THREAD

**Issue by pranathibl** [ARM-software/Tool-Solutions#2]
Hi,

scaling_max_freq of Hikey 960 is showing 903MHz for big cores and 533MHz for little cores. How to set scaling_max_frequency to available frequencies on hikey?

i have tried using : echo 1421000 > /sys/devices/system/cpu/cpu7/cpufreq/scaling_max_freq 
                      and  cpufreq-set -c 7 -u 1421000
 but none of them worked.
I also tried setting governor into performance mode, but it is still operating at 903MHz/533MHz.

**Comment by jasonrandrews** [comment]
I haven't tried anything myself yet, but a good discussion of frequency setting:

https://discuss.96boards.org/t/the-cpu-frequency-of-hikey960/3965/5

**Comment by pranathibl** [comment]
I have already tried as mentioned in the link above, but could not vary the scaling_max_freq.

**Comment by pranathibl** [comment]
We are able to set scaling_max_frequency on one of the Hikey boards (On other board i am still facing the issue).
Even on the working board, on which i am able to set max frequency - the frequency is dropping to a minimum value  while running any application even though the scaling governor is configured to "performance" mode with scaling_max_frequency set to maximum .
Do you have any suggestion on this issue?  Thanks.

**Comment by jasonrandrews** [comment]
Hi,

I would recommend to install the CPU frequency scaling tools:
$ sudo apt install cpufrequtils 

Use the [cpufreq-info](http://manpages.ubuntu.com/manpages/cosmic/man1/cpufreq-info.1.html) command to see the current values and monitor over time. 
You can also use [cpufreq-set](http://manpages.ubuntu.com/manpages/cosmic/man1/cpufreq-set.1.html) to change frequency and governor 

Let us know how this works out.
