### ISSUE TITLE
How to integrate the latest ARMCL 24.05 ?

### ISSUE THREAD

**Issue by esharkwang** [ARM-software/Tool-Solutions#234]
Could someone give me a hint how to upgrade the armcl version to 24.05?  I want to test the performance with Neoversion-V2 CPU.

Appreciate in advance.

**Comment by jondea** [comment]
To change the ACL version you can update the hash in the relevant`DOCKERFILE`s, for example for the PyTorch container, here is a commit which changed the ACL version https://github.com/ARM-software/Tool-Solutions/commit/674f47f9a2345f365cf7043545969d3d7369e045

**Comment by jondea** [comment]
I should also say that we will soon (next few weeks) be updating to a commit of ACL > 24.05. We currently do this for each monthly release.
