### ISSUE TITLE
Illegal instruction (core dumped) on cv2 import

### ISSUE THREAD

**Issue by tgsmith61591** [ARM-software/Tool-Solutions#24]
I came across this repo from [this blog post](https://community.arm.com/developer/tools-software/tools/b/tools-software-ides-blog/posts/aarch64-docker-images-for-pytorch-and-tensorflow) (which linked back to this git repository). I'm not sure whether this repo has any affiliation whatsoever with the `jasonrandrews` docker hub, so if not I apologize.

When I try to import open CV on an ARM64 machine, I get an illegal instruction error:

```bash
$ sudo docker run --rm -it -v `pwd`:/app -w / jasonrandrews/tensorflow-v2:latest /bin/bash
ubuntu@f3bdbb4d4682:/$ $VENV_DIR/bin/python -c 'import cv2'
Illegal instruction (core dumped)
```

I'm running this on a publicly available AMI on EC2: `ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-arm64-server-20190814 (ami-0fb0129cd568fe35f)`. Interestingly, if I run the exact same sequence of commands on my Macbook, I get no such error.

**Comment by nSircombe** [comment]
Hi @tgsmith61591,

You've come to the right place, @jasonrandrews' docker-hub images were built from the scripts in this repo.

I'll take a look and get back to you, I don't think this is something we've been before.

What kind of instance are you running? A1?

**Comment by tgsmith61591** [comment]
Thanks! Yep, it's an a1.4xlarge

**Comment by nSircombe** [comment]
Hi @tgsmith61591, just a quick update - we've been able to reproduce the issue on a1.4xlarge.

However, we've also tried building the image from scratch on A1 using the scripts in this repo, and `import cv2` appears to work fine. 

Also using when trying to reproduce the issue on a local AArch64 machine (ThunderX2), `import cv2` in the DockerHub image works!

So, a bit more investigation required - we'll get back to you!

**Comment by jasonrandrews** [comment]
I'm also taking a look at the problem now. I tried 2 different machines and one ran fine and one had the illegal instruction. It's possible the libopencv is compiled for a newer architecture compared to the machines that are failing. My failing machine also had a Cortex-A72 (same as A1) and the passing machine is the Qualcomm 8cx. I built the docker images on AWS M6g and they should probably have been built on A1 to run on A1. I have some more things to try.

**Comment by jasonrandrews** [comment]
We have confirmed that building docker images on A1 and running them on A1 is fine. The build scripts will set -mcpu=native wherever possible which leads to -mtune=native and -march=native and creates backward compatibility problems when images are built on M6g or C6g and run on A1. I put a couple of new images from my testing in my Docker hub account you can use which were built on A1. There is jasonrandrews/tensorflow-v2-a1 to replace the one you tried. If you want to see the development image use jasonrandrews/tensorflow-dev-v2-a1

**Comment by nSircombe** [comment]
Hi @tgsmith61591 - could you confirm if these new images resolve your issue, if it looks good then we'll close this ticket.

**Comment by tgsmith61591** [comment]
I've confirmed this is working with `jasonrandrews/tensorflow-v2-a1:latest`. Thanks!
