### ISSUE TITLE
How to enable CUDA when installing pytorch using docker?

### ISSUE THREAD

**Issue by 4everZard** [ARM-software/Tool-Solutions#28]
I tried to build pytorch image using $ ./build.sh --build-type pytorch. But when I ran the image using docker run -it --init pytorch I found the CUDA is not available. 

![pytorch](https://user-images.githubusercontent.com/17968665/94504806-38d97200-023c-11eb-8f10-94ad8a17dd2e.png)
![cuda](https://user-images.githubusercontent.com/17968665/94506386-daae8e00-023f-11eb-8d21-d3daead7d15b.png)

OS version: Ubuntu 18.04.4 LTS
CUDA version: 10.2.89

**Comment by nSircombe** [comment]
Hi @4everZard,

Thanks for getting in touch.
At present these images are targeting on-CPU workloads only, future updates will likely focus on adding optimised BLAS and oneDNN backends, but there are no plans right now to add CUDA support.

**Comment by 4everZard** [comment]
Thanks for letting me know！
