### ISSUE TITLE
ssh does not work after reboot

### ISSUE THREAD

**Issue by ivsrihari** [ARM-software/Tool-Solutions#3]
I followed instructions at below link to install ubuntu on Hikey960.
https://github.com/ARM-software/Tool-Solutions/tree/master/ml-tool-examples/hikey960-ubuntu

I am trying to connect to the new hikey board with ssh. After every reboot, I have to manually create /var/run/sshd folder and then start ssh service on the hikey960 board. Without these commands, ssh to hikey board does not work.

**Comment by jasonrandrews** [comment]
This should be fixed now by a change to config-fs.sh 

It needed a chown on the root file system.
