### ISSUE TITLE
Building ARM NN for ONNX environment

### ISSUE THREAD

**Issue by GAnto85** [ARM-software/Tool-Solutions#5]
Hi, i am trying to build ARM NN for ONNX environment using your script. I modified your bash script to include onnx libraries but i'm going through some issues. Do you suggest me to cut out the tensorflow part? Anyway i don't need TF for my purposes. 
How would you modify your script to include the ONNX parser?
Thank you.

**Comment by jasonrandrews** [comment]
Hi, 

You can remove the TensorFlow part and substitute with the ONNX in it's place. 

I would look at the [ONNX article on Arm Developer](https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-onnx/single-page) and plug in the "Generate the ONNX protobuf source files" instead of the TensorFlow section in the current script. 

As time allows we would like to add ONNX and Cafe to the script also. 

Thanks,
Jason

**Comment by GAnto85** [comment]
Hi, 
i've tried it but there is some issue around the end of the script, while building arm nn: 
![image](https://user-images.githubusercontent.com/39409379/56135174-7129b980-5f90-11e9-9ebe-d6c8387aef94.png)
I've tried everything, different versions, different compiler options to avoid the errors , but still nothing. Now i'm trying something completely different but i doubt it will work.

**Comment by jasonrandrews** [comment]
I'm looking at this now, are you cross-compiling on x86 or native compiling on Arm?

**Comment by GAnto85** [comment]
x86 on my virtual machine

**Comment by jasonrandrews** [comment]
I made a new script called [build-armnn-onnx.sh](https://github.com/ARM-software/Tool-Solutions/blob/master/ml-tool-examples/build-armnn/build-armnn-onnx.sh) 

It works for me both cross compiling on x86 and on an Arm64 board. 

$ ./build-armnn-onnx.sh -a arm64-v8a -o 0 

To get onnx to work I used the latest Arm Compile Library and Arm NN.

**Comment by GAnto85** [comment]
Thank you so much , this is awesome! I'm gonna try the script tomorrow and let you know how it goes! I will try crosscompiling for armv7 and v8 also, anyway i can use either a zc706 or a ultrascale+ .  Thank you again!

**Comment by GAnto85** [comment]
Did the UnitTests work for you?

**Comment by jasonrandrews** [comment]
Yes, but I only ran the armv8 version on a laptop where I did a native compile, I didn't try the cross compiled build by copying it over to an Arm board. 

$ ./UnitTests  
Running 1144 test cases...

*** No errors detected

**Comment by GAnto85** [comment]
ok I see I will try it out

**Comment by GAnto85** [comment]
Hi ,
I built ARMNN on my x86_64 ubuntu 16.04.
I crosscompiled it to be executed on aarch64.
I copied the folder armnn/build into the board's storage device and i'm trying to run "./UnitTests" from there.
I keep getting this :
libprotobuf.so.18: cannot open shared object file: No such file or directory
even though i added such library to "/usr/lib" and " /lib/" and also "/usr/local/lib" and added these paths in the file /etc/ld.so.conf.d/libarmnn.conf and exectuted "sudo ldconfig".
Maybe i should copy the whole armnn-devenv folder into the board? Or what i did is enough?

**Comment by GAnto85** [comment]
Hi,  finally i succesfully ran the UnitTests.
The next step for me is making my own program and run it.  The problemis compiling. I admit i'm not good at it so i am looking for some advice.
For now i just want to compile the OnnxMobileNet-Armnn test in the folder "test".
In order to compile it i am opening a terminal inside the folder "OnnxMobileNet-Armnn" and i'm writing the following command on the terminal:

aarch64-linux-gnu-g++ OnnxMobileNet-Armnn.cpp -I ../../src/armnnUtils/ -I ../../src/backends/backendsCommon/ -I ../../include/ -std=c++11 -L /home/nur/armnn-devenv/armnn/build/ -llibarmnn.so -llibarmnnUtils.a -llibarmnnOnnxParser.so -o MOBILENET

I am including a few folders required to compile it and the libraries.
I am getting this error :

In file included from ../InferenceTest.hpp:9:0,
from OnnxMobileNet-Armnn.cpp:5:
../InferenceModel.hpp:20:46: fatal error: backendsCommon/BackendRegistry.hpp: No such file or directory
compilation terminated.

This is weird because i included that directory. Anybody knows what's going on? Thanks!

**Comment by GAnto85** [comment]
I also tried to compile SimpleSample.cpp including paths and libraries but i get some errors. It makes no sense to me.

**Comment by GAnto85** [comment]
I resolved the previous error including a Flag in the compiler but now i got this :
![image](https://user-images.githubusercontent.com/39409379/56662358-108f3080-66a4-11e9-993a-0e9aec1e5e7d.png)
Seems like the linker is failing at something.

**Comment by jasonrandrews** [comment]
Hi, 

I gave it a try also, but didn't succeed yet. The application depends on the testing framework and you are likely missing some .cpp files from the tests/ directory. The CMakeLists.txt file is a clue of what needs to be added. I'll check if there is a better stand-alone example for ONNX that would be easier to learn from.

**Comment by jasonrandrews** [comment]
On your screenshot -lboost_program_options -lboost_filesystem are needed for sure but you will probably still have some undefined symbols.

**Comment by GAnto85** [comment]
Hi, thanks for your reply. I realized is better if i make my own application, because in that case i only have to link armnn lib and some includes. It got compiled and ran easily.  I just have to find some functions to preprocess and load an image in the input tensor and then i gotta find a way to link the label list to the output vector in order to choose the right class being classified.

**Comment by jasonrandrews** [comment]
I agree, that's a better way to learn how to use the library.
