### ISSUE TITLE
Frequency above scaling_max_freq?

### ISSUE THREAD

**Issue by linuxguy1212** [ARM-software/Tool-Solutions#55]
Hi

is it possible for the Governor or Userspace to "request" a frequency which is higher than the value "scaling_max_freq"? And if yes, what would happen then?

Thank you for all the help!

**Comment by jasonrandrews** [comment]
Hi, you can change the max frequency in Linux. This is typically done either by echo a new value to /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq or by using [cpufreq-set](https://linux.die.net/man/1/cpufreq-set) command. If you search for documentation on Linux CPUFreq you can read more.
