### ISSUE TITLE
docker tensorflow-aarch64 build fail numpy/scipy

### ISSUE THREAD

**Issue by cybersax2** [ARM-software/Tool-Solutions#56]
While building docker, fail due to permission denied at 

```
# Build numpy from source, using OpenBLAS for BLAS calls
COPY scripts/build-numpy.sh $PACKAGE_DIR/.
COPY patches/site.cfg $PACKAGE_DIR/site.cfg
RUN $PACKAGE_DIR/build-numpy.sh
```

solved by adding exec permission on build-numpy.sh after copying: 

```
# Build numpy from source, using OpenBLAS for BLAS calls
COPY scripts/build-numpy.sh $PACKAGE_DIR/.
COPY patches/site.cfg $PACKAGE_DIR/site.cfg
RUN sudo chmod +x $PACKAGE_DIR/build-numpy.sh
RUN $PACKAGE_DIR/build-numpy.sh
```
same holds for scipy.

**Comment by nSircombe** [comment]
Hi @cybersax2.

Thanks for your bug report. Could you confirm that you've observed this with the current head of master? I think this is an old,  glitch that's fine now. Certainly I've been unable to reproduce, the `build-numpy.sh` and `build-scipy.sh` scripts both appear to have the right permissions both in the original checkout and inside the `tools` image.

**Comment by cybersax2** [comment]
Hi @nSircombe 

I can confirm I am working on head of master (could be platform specific though, I'm running the build on a Jetson).  Easily solved, I just wanted to report it.
