### ISSUE TITLE
Error when compiling image or speech example for corstone 300 tflite example 

### ISSUE THREAD

**Issue by COTASPAR** [ARM-software/Tool-Solutions#57]
[This](https://github.com/ARM-software/Tool-Solutions/tree/master/docker/tensorflow-lite-corstone-fvp) example doesn't seem to work any more. The following command `./build_tflite_micro_app.sh -t m55+u55 -u img_class -i cat ` yields the following error:

--
Warning: L9931W: Your license for feature ds_compiler_eval20201 will expire in 30 days
Error: L6218E: Undefined symbol ethosu_init_v2 (referred from test_runner_test.o).
Error: L6218E: Undefined symbol ETHOSU_PMU_CNTR_Enable (referred from micro_interpreter.o).
Error: L6218E: Undefined symbol ETHOSU_PMU_CYCCNT_Reset (referred from micro_interpreter.o).
Error: L6218E: Undefined symbol ETHOSU_PMU_EVCNTR_ALL_Reset (referred from micro_interpreter.o).
Error: L6218E: Undefined symbol ETHOSU_PMU_Enable (referred from micro_interpreter.o).
Error: L6218E: Undefined symbol ETHOSU_PMU_Get_CCNTR (referred from micro_interpreter.o).
Error: L6218E: Undefined symbol ETHOSU_PMU_Get_EVCNTR (referred from micro_interpreter.o).
Error: L6218E: Undefined symbol ETHOSU_PMU_Set_EVTYPER (referred from micro_interpreter.o).
Error: L6218E: Undefined symbol ethosu_invoke_v2 (referred from ethosu.o).
Error: L6218E: Undefined symbol ethosu_irq_handler (referred from boot.o).
Finished: 0 information, 6 warning and 10 error messages.
armclang: warning: Your license for feature ds_suite_eval will expire in 30 days [-Wlicense-management]
armclang: warning: Your license for feature ds_compiler_eval20201 will expire in 30 days [-Wlicense-management]
armclang: error: linker command failed with exit code 1 (use -v to see invocation)
tensorflow/lite/micro/examples/test_runner/Makefile.inc:41: recipe for target 'tensorflow/lite/micro/tools/make/gen/fvp_cortex-m55/bin/test_runner_test' failed
make: *** [tensorflow/lite/micro/tools/make/gen/fvp_cortex-m55/bin/test_runner_test] Error 1
--

Any ideas how to fix this?

Best regards,

Name: Carlo Grisafi 
Email: carlo.grisafi@arm.com

**Comment by pareenaverma** [comment]
Hi Carlo, can you close this when you get a chance as we concluded it was a licensing setup issue.
