### ISSUE TITLE
SciPy version 1.4.1 is too old, time to bump to new version

### ISSUE THREAD

**Issue by sanje2v** [ARM-software/Tool-Solutions#64]
SciPy version specified in Docker file for Tensorflow aarch64 is more than 1.5 years old as of this writing. Even, scipy-pandas requires at least 1.5.1. I successfully, compiled SciPy version 1.6.3 from source without issue.

Think it's time to bump its version number in the Dockerfile.

**Comment by nSircombe** [comment]
Hi @sanje2v 
Yes, you're entirely right, our SciPy version is out-of-date and (over) due a refresh. However, there's a dependency problem here that stopped us changing the version number when we updated other elements of the Python stack. As far as I can remember, the specific version of TF we have, 2.3.0, has an explicit dependency on SciPy 1.4.1 - this is gone with later TF releases.
Once the TF version that we include has been updated (most likely to 2.5) we will be able to update SciPy.

**Comment by sanje2v** [comment]
That's unfortunate. Is there any ETA of the next TensorFlow release dockerfile might be?

After commenting on this question, you may close this thread, if you like.

**Comment by nSircombe** [comment]
We're trying to update monthly, there should be an update mid June, although this will only be minor, and the TF version will stay at 2.3. TF 2.5 should be part of this build in July - assuming there are no serious issues encountered.

**Comment by nSircombe** [comment]
With the last set up updates, the default SciPy version is now set to 1.5.2.
