### ISSUE TITLE
Cache configuration of Eigen library + TF

### ISSUE THREAD

**Issue by asharma-ampere** [ARM-software/Tool-Solutions#73]
Default Cache configuration of Eigen library is not as per N1. To get best performance out of Eigen, cache line configuration in "eigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h" must be as per hardware. 

By default L1 is 16K (const std::ptrdiff_t defaultL1CacheSize). It should be 64K for N1

This is also applicable for L2 and L3. it must be set as per hardware configuration

**Comment by nSircombe** [comment]
Hi @asharma-ampere,

I've been taking a look at this, and it's fairly straight forward to set the L1/2/3 cache sizes during the TF build by setting `--cxxopt=-DEIGEN_DEFAULT_L1_CACHE_SIZE=64*1024` (similarly for L2 & 3). Note: there is a small mistake (recently fixed - https://gitlab.com/libeigen/eigen/-/commit/297f0f563d916260665d7fadc017f94f1a5e7a03) in the version of Eigen that TensorFlow picks up which needs to be patched.
I have a patch ready that does this all and integrates the setting of the L1/2/3 caches into the `cpu_info.sh` script which currently sets appropriate `-mcpu`, `-mtune` etc. flags for the target.

However, there are a couple of issues that you might be able to comment on:
- I had previously looked at setting Eigen caches, and only saw an average uplift of ~4% using the `tf_cnn_benchmark` with TF 1.x.
- The perf. gain I see from these changes on c6g is small, just a couple of ms in single image latency.
- Adding the cache size setting to `cpu_info.sh` in this Tool Solutions build isn't a problem, however this script uses `/proc/cpuinfo` to decide which options to pick. As I understand it, this would not be able to differntiate between different implementations of Neoverse-N1, which might, never-the-less, benefit from different cache sizes (thinking of L3 in particular of course).

**Comment by asharma-ampere** [comment]
For cache size /proc/cpuinfo may not have all the details. Can you try lshw (if you have sudo access of system)

for 1P system:
sudo lshw -C memory | grep -i -C 1 "L1\|L2\|L3" | grep -i size

for 2P system (we need it just once)
sudo lshw -C memory | grep -i -C 1 "L1\|L2\|L3" | grep -i size | head -n 3

On my system output looks like this:
# sudo lshw -C memory | grep -i -C 1 "L1\|L2\|L3" | grep -i size | head -n 3
       size: 64KiB
       size: 1MiB
       size: 32MiB

**Comment by nSircombe** [comment]
Hi,

I don't think that will be practical - we can't really add a step which necessitates sudo access to the build - I'm also not sure how portable this would be.

**Comment by nSircombe** [comment]
Hi @asharma-ampere,

This [commit](https://github.com/ARM-software/Tool-Solutions/commit/35f587f97aa1feab5f01da1ab9bd17c87206d8dc#diff-d548c5b83fa61d8e3bd86ad42a7ffea9b7c86e3f9d8095c1577d3e1270bb9420) makes it possible to set the L1,2,3 cache sizes used in the Eigen GEBP kernel when you build the image.

The values taken are defined for various targets in `cpu_info.sh`, so can be adjusted there. The script will then pick the appropriate set based on the cpu implementor and part number defined in `/proc/cpuinfo`. Alternatively you can pick a target using `--build-target`, which will allow you to force the build to pick up 'custom' values defined `cpu_info.sh`.

Please give it a go and let me know how you get on.
